# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: "3.16"
    environment:
      SCHEDULE: ${SCHEDULE} # optional
      BACKUP_KEEP_DAYS: 7 # optional
      PASSPHRASE: ${PASSPHRASE} # optional
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: backup
      POSTGRES_HOST: postgres # Network alias of PostgreSQL container, if needed
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - backup_data:/path/where/backup/stores # Assuming the backup process writes to a specific path

volumes:
  postgres_data:
    driver: local
  backup_data:
    driver: local
